---
title: "About"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

We characterised the gene expression profiles of muscle cultures derived from two donors with MND and two non-neurodegenerative donors.

See the methods section of [our paper](https://actaneurocomms.biomedcentral.com/articles?query=Impaired+signaling+for+neuromuscular+synaptic+maintenance+is+a+feature+of+Motor+Neuron+Disease&volume=&searchType=&tab=keyword) for details on the isolation of single-nuclei from myotubes for RNA sequencing.

This work is made possible by Peter Noakes, William Phillips, Shyuan Ngo ([\@NgoShyuan](https://twitter.com/NgoShyuan "Shyuan Ngo's Twitter")), Dominique Power ([\@Dom_T\_Power](https://twitter.com/Dom_T_Power "Dominique Power's Twitter")), Jeryn Chang ([\@JerynChang](https://twitter.com/JerynChang "Jeryn Chang's Twitter")), Jessica Mar ([\@jessicacmar](https://twitter.com/jessicacmar "Jessica Mar's Twitter")), and Atefeh Taherian Fard ([\@AtiFard](https://twitter.com/AtiFard "Atehfeh Taherian Fard's Twitter")).

We are grateful to the Institute of Molecular Biosciences sequencing facility for assisting with the generation of single nuclei sequencing data. This work was supported by Motor Neuron Disease Research Australia (MNDRA, GIV 1842 to PGN, MNDRA Charcot Grant to STN, and PhD Scholarship top-up Grant to JC), National Health & Medical Research Council Australia (NHMRC 1188169 to PGN WDP, and 1101085 to STN), and start-up funds to STN and JCM from the Australian Institute for Bioengineering and Nanotechnology. STN acknowledges support through the Scott Sullivan MND Fellowship (2015-2020, MND & Me Foundation, RBWH Foundation), and a FightMND Fellowship (2020-2023).
